title:              Kez Lab
email:              kez.lab.dev@gmail.com
description:        Android, Kotlin, AI, Web 개발 관련 기술 블로그
author:             Kez
baseurl:            ""
url:                "https://kez-lab.github.io"

# SEO Settings
keywords:           "Android, Kotlin, 코틀린, 안드로이드, 인공지능, AI, 웹개발, Web, 개발자, 프로그래밍, 개발블로그"
lang:               ko_KR
locale:             ko_KR
author_image:       /img/author.jpg

# Social Profiles
twitter_username:   
github_username:    kez-lab
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
