# Site settings
title:          "KEZ Lab"
description:    "Android, Kotlin, AI, Web 개발 기술을 공유하는 기술 블로그 | 안드로이드, 코틀린, 인공지능, 웹 개발"
baseurl:        ""
url:            "https://kez-lab.github.io"
lang:           "ko-KR"
locale:         "ko_KR"
author:         "KEZ"
logo:           "/assets/images/kez-logo.png"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         KEZ
  url:          https://kez-lab.github.io
  email:        kejprogramer0909@gmail.com
  twitter:      # 트위터 계정이 있다면 추가
  github:       kez-lab
  linkedin:     # 링크드인 계정이 있다면 추가

# Social
social:
  name: KEZ Lab
  links:
    - https://github.com/kez-lab
    # - https://twitter.com/ # 트위터 계정이 있다면 추가
    # - https://www.linkedin.com/in/ # 링크드인 계정이 있다면 추가

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
# URL 구조 최적화
permalink:      /:title/

# 또는 카테고리 포함
# permalink:      /:categories/:title/
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         kez-lab